#!/bin/bash

# to be called from /etc/network/if-{up,post-down}.d

# MODE=stop
# PHASE=post-down

# MODE=start
# PHASE=post-up
# etc.

set -eu

export PATH=/opt/chj/openvpn-tunnel-setup:/opt/chj/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PERL5LIB=/opt/chj/perllib/

case "$MODE" in
    start)
    vpn-tunnel startrouting
    ;;
    stop)
    vpn-tunnel stoprouting
    ;;
    *)
    echo "ignoring mode '$MODE'"
    ;;
esac
